apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct3-app
  namespace: ct3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct3-app
  template:
    metadata:
      labels:
        app: ct3-app
    spec:
      containers:
        - name: ct3-app
          image: difagume/ct3-app
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ct3-app
  namespace: ct3-app
spec:
  selector:
    app: ct3-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
# si se cambia el nombre del servicio se debe cambiar en los archivos:
# 1. nginx --> default.conf
# 2. docker-compose.yml
#     services:
#       ct3-app: