apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct3-app-nginx
  namespace: ct3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct3-app-nginx
  template:
    metadata:
      labels:
        app: ct3-app-nginx
    spec:
      containers:
        - name: ct3-app-nginx
          image: difagume/ct3-app-nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ct3-app-nginx
  namespace: ct3-app
spec:
  type: NodePort
  selector:
    app: ct3-app-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
